config/routes.rb
resources :emailtemplates

resources :projects do
  resources :emailtemplates, :controller => 'emailtemplates',
            :only => [:index, :new, :create, :edit, :update, :destroy]
end 

app/models/emailtemplate.rb
class Emailtemplate < ActiveRecord::Base
  belongs_to :project

  has_one :issue_status
end

app/controllers/emailtemplates_controller.rb
class EmailtemplatesController < ApplicationController
  default_search_scope :emailtemplates
  model_object Emailtemplate
  before_filter :find_model_object, :except => [:new, :create, :index]
  before_filter :find_project_from_association, :except => [:new, :create, :index]
  before_filter :find_optional_project
  menu_item :templates

  def index
     @emailtemplates = Emailtemplate.where(project_id: @project.id)
  end

  def new
    @emailtemplate = Emailtemplate.new
    render :action => :edit
  end

  def create
    @emailtemplate = Emailtemplate.create(ad_params)
    if @emailtemplate.save
      redirect_to project_emailtemplates_path(@emailtemplate.project_id)
    else
      render :action => 'edit'
    end

  end

  def edit
    @emailtemplate = Emailtemplate.find(params[:id])
  end

  def update
    @emailtemplates = Emailtemplate.find(params[:id])
    @emailtemplates.update_attributes(ad_params)
    if @emailtemplates.save
      redirect_to project_emailtemplates_path(@project)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @emailtemplates = Emailtemplate.find(params[:id])
    @emailtemplates.destroy
    redirect_to project_emailtemplates_url
  end

  private

  def find_optional_project
    return true unless params[:project_id]
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
  def ad_params
    params.require(:emailtemplate).permit(:project_id, :email, :subject, :body, :issue_statuse_id)
  end
end

app/helpers/emailtemplates_helper.rb
module EmailtemplatesHelper
end

app/views/emailtemplates/_form.html.erb
<h2><%= @emailtemplate.new_record? ?
            l(:emailtemplate_new) :
            l(:emailtemplate_edit) %></h2>
<%= error_messages_for @emailtemplate %>


<%= labelled_form_for @emailtemplate do |f| %>
    <div class="box tabular">
      <fieldset>
      <div>
       <p>
       	 <label for = "project_id"> Project </label>
          <%= f.collection_select :project_id, Project.all, :id, :name, {:selected => @project.id}  %>
       </p>
       	
       <div class="c">

        <p >
          	<%= f.text_field :email %>
        </p>
       
       	<p>
       		<%= f.text_field :subject %>
        </p>
        <p>
        	<%= f.text_area :body %>
        </p>
        </div>
        <p>
        <label for = "issue_statuse"> Status to </label>
          <%= f.collection_select :issue_statuse_id, IssueStatus.all, :id, :name  %>
        </p>


        <%= submit_tag l(:button_save) %>
      <%= link_to l(:button_cancel), emailtemplates_path %>
      </fieldset>
    </div>
<% end %>

app/views/emailtemplates/edit.html.erb
<%= render 'form'%>

app/views/emailtemplates/index.html.erb
<div class="contextual">
  <%= link_to l(:label_emailtemplate_new),
              {:action => 'new'},
              :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_emailtemplate)%></h2>

<table class="list templates">
  <thead>
  <tr>
    <th><%=l(:email)%></th>
    <th><%= l(:subject) %></th>
    <th><%= l(:status) %></th>
   
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @emailtemplates.each do |template| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="templates-title"><%= link_to h(template.email),
                                                      { :action => :edit, :id => template.id } %></td>
        <td class="templates-content"><div><%= simple_format h(template.subject) %></div></td>
        <td class="templates-status"><div><%= simple_format h(IssueStatus.find(template.issue_statuse_id).name) %>
        </div></td>

        <td class="buttons">
          <%= link_to l(:button_edit),
                      {
                          :controller => 'emailtemplates',
                          :action => 'edit',
                          :id => template.id
                      },
                      :class => 'icon icon-edit' %>
          <%= link_to l(:button_delete),
                      {
                          :controller => 'emailtemplates',
                          :action => 'destroy',
                          :id => template.id
                      },
                      :method => :delete,
                      :confirm => l(:text_are_you_sure),
                      :class => 'icon icon-del' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/emailtemplates/new.html.erb
<%= render 'form' %>

app/views/settings/_settings_emailtemplate.html.erb
<h2><%=l(:label_emailtemplate)%></h2>

app/views/settings/emailatemplates.html.erb
<h2><%=l(:label_emailtemplate)%></h2>